server:
  port: 8083

spring:
  application:
    name: storage-service

  datasource:
    url: jdbc:postgresql://localhost:5433/storage_db
    username: postgres
    password: pass

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/autosalon/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
grpc:
  server:
    port: 9091

